INSERT INTO DEPARTAMENTO VALUES (1,1 , 'Dep1', 'Dep1'); 
INSERT INTO DEPARTAMENTO VALUES (2,2 , 'Dep2', 'Dep2'); 

INSERT INTO FUNCION (ID_FUNCION, DESCRIPCION, NOMBRE, ID_DEPARTAMENTO) VALUES  (1, 'FUNCION1', 'NOMBRE FUN1',1);
INSERT INTO FUNCION (ID_FUNCION, DESCRIPCION, NOMBRE, ID_DEPARTAMENTO) VALUES  (2, 'FUNCION2', 'NOMBRE FUN2',1);
INSERT INTO FUNCION (ID_FUNCION, DESCRIPCION, NOMBRE, ID_DEPARTAMENTO) VALUES  (3, 'FUNCION3', 'NOMBRE FUN3',1);
INSERT INTO FUNCION (ID_FUNCION, DESCRIPCION, NOMBRE, ID_DEPARTAMENTO) VALUES  (4, 'FUNCION4', 'NOMBRE FUN4',2);
INSERT INTO FUNCION (ID_FUNCION, DESCRIPCION, NOMBRE, ID_DEPARTAMENTO) VALUES  (5, 'FUNCION5', 'NOMBRE FUN5',2);

INSERT INTO EMPLEADO (ID_EMPLEADO, ACTIVO, APELLIDOS, CORREO,NOMBRE,NUMERO_DOCUMENTO,SALARIO,TELEFONO,ID_DEPARTAMENTO) VALUES (1,'TRUE','APELLIDO1','CORREO1','NOMBREEMPLE1','DOCUMENTO EMPLE1',50000,'TELEFONO EMPL1',1);

INSERT INTO EMPLEADO (ID_EMPLEADO, ACTIVO, APELLIDOS, CORREO,NOMBRE,NUMERO_DOCUMENTO,SALARIO,TELEFONO,ID_DEPARTAMENTO) VALUES (2,'FALSE','APELLIDO2','CORREO2','NOMBREEMPLE2','DOCUMENTO EMPLE1',150000,'TELEFONO EMPL2',2);

INSERT INTO EMPLEADO_FUNCION (ID_EMPLEADO_FUNCION,ID_EMPLEADO,ID_FUNCION)VALUES(1,1,1);
INSERT INTO EMPLEADO_FUNCION (ID_EMPLEADO_FUNCION,ID_EMPLEADO,ID_FUNCION)VALUES(2,1,2);
INSERT INTO EMPLEADO_FUNCION (ID_EMPLEADO_FUNCION,ID_EMPLEADO,ID_FUNCION)VALUES(3,2,4);


